In [26]:
import numpy as np

def gauss_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

   
    for i in range(n):
    
        max_row = np.argmax(abs(A[i:, i])) + i
        A[[i, max_row]] = A[[max_row, i]]
        b[[i, max_row]] = b[[max_row, i]]

        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

In [27]:

A = np.array([
    [10, 7, 8, 7],
    [7, 5, 6, 5],
    [8, 6, 10, 9],
    [7, 5, 9, 10]
], dtype=float)

A_tilde = np.array([
    [10, 7, 8.1, 7.2],
    [7.08, 5.04, 6, 5],
    [8, 6, 9.98, 9],
    [6.99, 4.99, 9, 9.98]
], dtype=float)


b = np.array([32, 23, 33, 31], dtype=float)
b_tilde = np.array([32.1, 22.9, 33.1, 30.9], dtype=float)

# Lösungen
x = gauss_elimination(A.copy(), b.copy())
x_tilde = gauss_elimination(A_tilde.copy(), b_tilde.copy())

print("x =", x)
print("x_tilde =", x_tilde)

# Vergleich
print("Differenz ||x - x_tilde|| =", np.linalg.norm(x - x_tilde))

x = [1. 1. 1. 1.]
x_tilde = [  72.5273 -117.7925   31.5963  -17.2994]
Differenz ||x - x_tilde|| = 143.17408351098544


In [28]:
np.set_printoptions(precision=4, suppress=True)

def pretty(M, decimals=4):
    return np.round(M, decimals)


A_inv = np.linalg.inv(A)
A_tilde_inv = np.linalg.inv(A_tilde)

print("\nA^-1:\n", pretty(A_inv))
print("\nA_tilde^-1:\n", pretty(A_tilde_inv))


eig_A = np.linalg.eigvals(A)
eig_A_tilde = np.linalg.eigvals(A_tilde)

print("\nEigenwerte von A:", np.round(eig_A, 6))
print("Eigenwerte von A_tilde:", np.round(eig_A_tilde, 6))


def compute_norms(M):
    return tuple(
        round(float(np.linalg.norm(M, ord)), 4)
        for ord in [1, 2, np.inf]
    )

print("\nNormen von A (1,2,inf):", compute_norms(A))
print("Normen von A_tilde:", compute_norms(A_tilde))
print("Normen von A^-1:", compute_norms(A_inv))
print("Normen von A_tilde^-1:", compute_norms(A_tilde_inv))



A^-1:
 [[ 25. -41.  10.  -6.]
 [-41.  68. -17.  10.]
 [ 10. -17.   5.  -3.]
 [ -6.  10.  -3.   2.]]

A_tilde^-1:
 [[ 339.4225 -533.6026  134.2094  -98.5685]
 [-562.5467  885.1202 -223.0309  163.5284]
 [ 143.8088 -226.681    57.8798  -42.3784]
 [ -86.1457  135.5973  -34.6811   25.5905]]

Eigenwerte von A: [30.2887  3.8581  0.0101  0.8431]
Eigenwerte von A_tilde: [30.3783  3.7869  0.0008  0.834 ]

Normen von A (1,2,inf): (33.0, 30.2887, 33.0)
Normen von A_tilde: (33.08, 30.3789, 32.98)
Normen von A^-1: (136.0, 98.5217, 136.0)
Normen von A_tilde^-1: (1781.0011, 1307.2579, 1834.2262)
