In [6]:
#EX2A:

import numpy as np

A = np.array([
    [10, 7, 8, 7],
    [7, 5, 6, 5],
    [8, 6, 10, 9],
    [7, 5, 9, 10]
], dtype=float)

b = np.array([32, 23, 33, 31], dtype=float)

A, b

(array([[10.,  7.,  8.,  7.],
        [ 7.,  5.,  6.,  5.],
        [ 8.,  6., 10.,  9.],
        [ 7.,  5.,  9., 10.]]),
 array([32., 23., 33., 31.]))

In [7]:
# Check symmetry
print("Symmetric:", np.allclose(A, A.T))

# Check positive definiteness via Cholesky
try:
    np.linalg.cholesky(A)
    print("Positive definite: True")
except np.linalg.LinAlgError:
    print("Positive definite: False")

Symmetric: True
Positive definite: True


In [8]:
#B:

def cholesky(A):
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1):
            s = 0
            for k in range(j):
                s += L[i][k] * L[j][k]

            if i == j:
                L[i][j] = np.sqrt(A[i][i] - s)
            else:
                L[i][j] = (A[i][j] - s) / L[j][j]

    return L

L = cholesky(A)
print("L =\n", L)

L =
 [[3.16227766 0.         0.         0.        ]
 [2.21359436 0.31622777 0.         0.        ]
 [2.52982213 1.26491106 1.41421356 0.        ]
 [2.21359436 0.31622777 2.12132034 0.70710678]]


In [9]:
#C:

y = np.linalg.solve(L, b)

x = np.linalg.solve(L.T, y)

print("Solution x =", x)

Solution x = [1. 1. 1. 1.]


In [10]:
# Check Ax ≈ b
print("Ax =", A @ x)
print("b  =", b)

Ax = [32. 23. 33. 31.]
b  = [32. 23. 33. 31.]
